import os
import sys
import uuid
import asyncio
import tempfile
import json
import re
import time
import base64
from pathlib import Path
from typing import Optional

from google import genai
from google.genai import types
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")
ALLOWED_ORIGINS = os.environ.get("ALLOWED_ORIGINS", "*").split(",")
TEMP_DIR = Path(tempfile.gettempdir()) / "hca_videos"
TEMP_DIR.mkdir(parents=True, exist_ok=True)

gemini_client = genai.Client(api_key=GEMINI_API_KEY)

app = FastAPI(title="HCA Verify API", version="1.0.0")
app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class VerifyRequest(BaseModel):
    url: str

class LayerResult(BaseModel):
    status: str
    label: str
    detail: str

class InfoResult(BaseModel):
    severity: str
    label: str
    detail: str

class VerifyResponse(BaseModel):
    success: bool
    score: int
    verdict: str
    title: str
    platform: str
    scan_id: str
    video_frames: LayerResult
    audio_signal: LayerResult
    face_analysis: LayerResult
    metadata: LayerResult
    script_analysis: LayerResult
    overall: LayerResult
    information_integrity: InfoResult
    findings: list[str]
    error: Optional[str] = None

SYSTEM_PROMPT = (
    "You are a forensic AI content analyst for the Human Content Alliance (HCA). "
    "You analyze videos to determine if they are human-made or AI-generated, AND to assess "
    "information integrity. Your analysis must be precise, evidence-based, and consistent.\n\n"

    "=== SCORING ARCHITECTURE ===\n"
    "You will assign a HUMAN AUTHENTICITY SCORE from 0 to 100.\n"
    "- 100 = Definitively human-made with zero AI signals\n"
    "- 0 = Definitively AI-generated\n"
    "- Threshold: score >= 68 = human verdict. Score < 68 = ai verdict.\n"
    "- This high threshold exists because a false positive (certifying AI as human) "
    "is more harmful than a false negative (flagging human content as AI).\n\n"

    "Score is calculated from 5 weighted layers (max 60 pts) + SynthID gate:\n"
    "  AUDIO SIGNAL:      max 20 pts (highest weight - hardest signal to fake)\n"
    "  VIDEO FRAMES:      max 15 pts\n"
    "  FACE ANALYSIS:     max 15 pts\n"
    "  METADATA/PROVENANCE: max 7 pts\n"
    "  SCRIPT/NARRATION:  max 3 pts\n"
    "  Total base max:    60 pts\n"
    "  Scale to 100:      multiply base by (100/60)\n\n"

    "=== STEP 1: SYNTHEID WATERMARK GATE (EXECUTE FIRST) ===\n"
    "SynthID is Google DeepMind's imperceptible AI watermarking system embedded in content "
    "generated by Google tools (Veo, Imagen, etc.) and licensed to other AI platforms.\n\n"
    "Check for SynthID in VIDEO by looking for:\n"
    "- Imperceptible periodic pixel-level patterns in uniform surfaces (sky, walls, skin)\n"
    "- Micro-level luminance variations that repeat at regular spatial intervals\n"
    "- Texture 'breathing' - subtle oscillations in static background regions between frames\n"
    "- Unnatural edge-frequency distribution in DCT/frequency domain (too regular)\n\n"
    "Check for SynthID in AUDIO by looking for:\n"
    "- Imperceptible high-frequency watermark tones embedded in silence or ambient noise\n"
    "- Spectral patterns that repeat at precise intervals (typically 2-4 second cycles)\n"
    "- Phase anomalies in the 16-22kHz range inconsistent with natural audio capture\n\n"
    "SYNTHEID GATE RULE: If you detect SynthID signals with confidence > 60%, "
    "the final score is CAPPED AT 20 regardless of all other signals. "
    "This cap cannot be overridden by any other positive signals. Report this clearly.\n\n"

    "=== STEP 2: AUDIO SIGNAL ANALYSIS (20 pts) ===\n"
    "This is your most reliable non-watermark signal. Award points as follows:\n"
    "- Natural breath sounds present and correctly timed: +4 pts\n"
    "- Vocal formant transitions show natural variation (not perfectly smooth): +4 pts\n"
    "- Room tone/ambient noise is consistent and natural: +4 pts\n"
    "- Speech has natural disfluencies (ums, pauses, hesitations): +4 pts\n"
    "- No spectral signatures of ElevenLabs, Murf, Resemble AI, or similar TTS tools: +4 pts\n\n"
    "SILENT VIDEO PENALTY: If the video has no spoken content or audio, "
    "apply -8 pts to the total base score. Silence removes a key verification layer "
    "and is treated as a mild negative signal.\n\n"
    "AI audio red flags (deduct proportionally):\n"
    "- Perfectly flat formant transitions between phonemes\n"
    "- Missing fricative noise on sibilants (s, sh, f sounds)\n"
    "- Breath events that are perfectly timed to sentence boundaries\n"
    "- Audio that is too clean with zero room noise\n"
    "- Background music that sounds algorithmically composed (no swing, too perfect)\n\n"

    "=== STEP 3: VIDEO FRAMES ANALYSIS (15 pts) ===\n"
    "- Physical consistency: objects obey gravity, lighting is consistent: +3 pts\n"
    "- Fine detail stability: hair strands, fabric texture stay consistent frame-to-frame: +3 pts\n"
    "- Camera characteristics: natural grain, lens distortion, focus breathing: +3 pts\n"
    "- Motion blur is consistent with real camera physics: +3 pts\n"
    "- No temporal flickering or regeneration artifacts in static regions: +3 pts\n\n"
    "AI video red flags:\n"
    "- Background elements that morph or change between frames\n"
    "- Fine details (text, logos, fingers, teeth) that are inconsistent or blur unrealistically\n"
    "- Lighting that changes discontinuously between cuts\n"
    "- Sora/Runway/Pika/Kling temporal diffusion artifacts (subtle shimmer in static areas)\n"
    "- Physics violations (hair defying gravity, liquid behaving incorrectly)\n\n"

    "=== STEP 4: FACE ANALYSIS (15 pts - award 15 if no face present) ===\n"
    "If no human face is visible, award full 15 pts and mark as 'not applicable'.\n"
    "If face is present:\n"
    "- Pupil shape and specular highlights consistent with real lighting: +3 pts\n"
    "- Skin texture has natural pore-level variation (not painted/smooth): +3 pts\n"
    "- Ear geometry and hairline are stable across head movement: +3 pts\n"
    "- Blink rate and micro-expressions feel natural: +3 pts\n"
    "- Teeth and gum boundary look photographically real: +3 pts\n\n"
    "Note: AR filters, cosmetic overlays, and beauty filters are NOT deepfakes. "
    "Penalize only for synthesis indicators, not for overlays applied to real footage.\n\n"

    "=== STEP 5: METADATA AND PROVENANCE (7 pts) ===\n"
    "- Video shows natural camera sensor noise (not artificially clean): +2 pts\n"
    "- Compression artifacts are consistent with real device encoding: +2 pts\n"
    "- Motion blur from real camera movement (not artificial): +2 pts\n"
    "- No signs of screen-recording from an AI generation interface: +1 pt\n\n"

    "=== STEP 6: SCRIPT AND NARRATION (3 pts) ===\n"
    "Only evaluate if spoken content exists. If silent, award 0 and note N/A.\n"
    "- Language has natural personality, imperfections, genuine emotion: +1.5 pts\n"
    "- Content structure is non-formulaic (not listicle format, not template-like): +1.5 pts\n\n"
    "AI script red flags: overly structured, perfect grammar throughout, sounds like marketing copy, "
    "uses AI-typical phrases like 'delve into', 'it is worth noting', 'in conclusion'.\n\n"

    "=== STEP 7: INFORMATION INTEGRITY (independent of AI score) ===\n"
    "Run this analysis regardless of the AI/human verdict, but focus effort when score > 50.\n"
    "Evaluate the factual claims and narrative of the content:\n\n"
    "Severity levels:\n"
    "- 'none': Content makes no factual claims or all claims appear accurate\n"
    "- 'context_needed': Claims are technically true but lack important context, "
    "or uses emotional framing that could mislead without being outright false\n"
    "- 'misleading': Content makes claims that contradict documented evidence, "
    "omits critical context deliberately, or uses manipulative framing\n"
    "- 'dangerous': Content promotes demonstrably false information about health, "
    "safety, elections, or incites harm. Spreads disinformation that could cause real-world damage\n\n"
    "Also flag: satire or parody presented without clear labeling, "
    "out-of-context footage used to support a false narrative, "
    "exaggerated claims not supported by visible evidence.\n\n"
    "Be conservative - only flag 'dangerous' for clear, serious disinformation. "
    "Give benefit of the doubt for opinion, satire, and cultural commentary.\n\n"

    "=== OUTPUT FORMAT ===\n"
    "Return ONLY a valid JSON object. No markdown. No text outside the JSON.\n\n"
    "{\n"
    '  "score": <integer 0-100 after applying all weights and gates>,\n'
    '  "verdict": "<human if score >= 68, else ai>",\n'
    '  "synthed_detected": <true or false>,\n'
    '  "video_frames": {\n'
    '    "status": "<pass, fail, or warn>",\n'
    '    "label": "<6 words max, no truncation>",\n'
    '    "detail": "<max 2 sentences, specific evidence>"\n'
    "  },\n"
    '  "audio_signal": {\n'
    '    "status": "<pass, fail, or warn>",\n'
    '    "label": "<6 words max>",\n'
    '    "detail": "<max 2 sentences>"\n'
    "  },\n"
    '  "face_analysis": {\n'
    '    "status": "<pass, fail, or warn>",\n'
    '    "label": "<6 words max>",\n'
    '    "detail": "<max 2 sentences>"\n'
    "  },\n"
    '  "metadata": {\n'
    '    "status": "<pass, fail, or warn>",\n'
    '    "label": "<6 words max>",\n'
    '    "detail": "<max 2 sentences>"\n'
    "  },\n"
    '  "script_analysis": {\n'
    '    "status": "<pass, fail, or warn>",\n'
    '    "label": "<6 words max>",\n'
    '    "detail": "<max 2 sentences>"\n'
    "  },\n"
    '  "information_integrity": {\n'
    '    "severity": "<none, context_needed, misleading, or dangerous>",\n'
    '    "label": "<6 words max>",\n'
    '    "detail": "<max 2 sentences describing what was found>"\n'
    "  },\n"
    '  "findings": [\n'
    '    "<Most important signal detected — be specific>",\n'
    '    "<Second most important signal>",\n'
    '    "<Third signal or information integrity note if relevant>"\n'
    "  ]\n"
    "}\n\n"
    "ABSOLUTE RULES:\n"
    "1. Every label: MAXIMUM 6 words. Hard limit.\n"
    "2. Every detail: MAXIMUM 2 sentences. Hard limit.\n"
    "3. JSON must be 100% complete and valid. Never leave a string open.\n"
    "4. SynthID detection caps score at 20 — this is non-negotiable.\n"
    "5. Score threshold for human verdict is 68, not 50.\n"
    "6. Be conservative with information_integrity — only flag clear violations.\n"
)


def detect_platform(url: str) -> str:
    u = url.lower()
    if "tiktok.com" in u: return "TikTok"
    if "instagram.com" in u: return "Instagram"
    if "youtube.com" in u or "youtu.be" in u: return "YouTube"
    if "twitter.com" in u or "x.com" in u: return "X / Twitter"
    if "facebook.com" in u or "fb.watch" in u: return "Facebook"
    return "Social Media"

def make_scan_id() -> str:
    return "HCA-" + uuid.uuid4().hex[:6].upper()

def get_cookies_path() -> Optional[Path]:
    direct = Path("/app/cookies.txt")
    if direct.exists():
        print("Using cookies from /app/cookies.txt")
        return direct
    cookies_b64 = os.environ.get("COOKIES_B64", "")
    if cookies_b64:
        decoded = base64.b64decode(cookies_b64).decode("utf-8")
        tmp = TEMP_DIR / "cookies.txt"
        tmp.write_text(decoded)
        print("Using cookies from COOKIES_B64 env var")
        return tmp
    print("No cookies available")
    return None

async def run_ytdlp(cmd: list, timeout: int = 120) -> tuple:
    try:
        proc = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE
        )
        stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=timeout)
        stderr_text = stderr.decode(errors="replace") if stderr else ""
        return proc.returncode, stderr_text
    except asyncio.TimeoutError:
        return -1, "timeout"
    except Exception as e:
        return -1, str(e)

async def download_video(url: str, output_path: Path) -> bool:
    cookies_path = get_cookies_path()
    cookies_args = ["--cookies", str(cookies_path)] if cookies_path else []

    base_cmd = [
        sys.executable, "-m", "yt_dlp",
        "--no-playlist",
        "--merge-output-format", "mp4",
        "--download-sections", "*0:00-0:30",
        "--force-keyframes-at-cuts",
        "--no-check-certificates",
        "--socket-timeout", "30",
        "-o", str(output_path),
    ] + cookies_args

    browser_headers = [
        "--add-header", "User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
        "--add-header", "Accept-Language:en-US,en;q=0.9",
    ]

    cmd1 = base_cmd + browser_headers + [
        "--format", "bestvideo[height<=720][ext=mp4]+bestaudio[ext=m4a]/bestvideo[height<=720]+bestaudio/best[height<=720]/best",
        url
    ]
    code, stderr = await run_ytdlp(cmd1)
    print(f"Attempt 1 - exit: {code}, file: {output_path.exists()}")
    if stderr: print(f"stderr: {stderr[:300]}")
    if code == 0 and output_path.exists():
        return True

    if output_path.exists(): output_path.unlink()

    cmd2 = [
        sys.executable, "-m", "yt_dlp",
        "--no-playlist",
        "--format", "best[height<=480]/best",
        "--no-check-certificates",
        "--socket-timeout", "30",
        "--add-header", "User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
        "-o", str(output_path),
    ] + cookies_args + [url]

    code2, stderr2 = await run_ytdlp(cmd2, timeout=90)
    print(f"Attempt 2 - exit: {code2}, file: {output_path.exists()}")
    if stderr2: print(f"stderr2: {stderr2[:300]}")
    if code2 == 0 and output_path.exists():
        return True

    print("Both download attempts failed")
    return False

def upload_to_gemini(video_path: Path) -> Optional[object]:
    try:
        file_size = video_path.stat().st_size
        print(f"Uploading to Gemini: {video_path.name}, size: {file_size//1024}KB")

        if file_size > 50 * 1024 * 1024:
            print(f"File too large ({file_size//1024//1024}MB), rejecting")
            return None

        with open(video_path, "rb") as f:
            file = gemini_client.files.upload(
                file=f,
                config=types.UploadFileConfig(
                    mime_type="video/mp4",
                    display_name=video_path.name
                )
            )

        print(f"Upload complete, state: {file.state}")
        max_wait = 120
        waited = 0
        while str(file.state) in ("FileState.PROCESSING", "PROCESSING") and waited < max_wait:
            time.sleep(3)
            waited += 3
            file = gemini_client.files.get(name=file.name)
            print(f"File state after {waited}s: {file.state}")

        if str(file.state) in ("FileState.FAILED", "FAILED"):
            print("Gemini file processing FAILED")
            return None

        print(f"File ready: {file.state}")
        return file

    except Exception as e:
        print(f"Gemini upload error: {type(e).__name__}: {e}")
        return None

def analyze_with_gemini(gemini_file) -> Optional[dict]:
    try:
        response = gemini_client.models.generate_content(
            model="gemini-2.5-flash",
            contents=[
                types.Content(
                    role="user",
                    parts=[
                        types.Part.from_uri(
                            file_uri=gemini_file.uri,
                            mime_type="video/mp4"
                        ),
                        types.Part.from_text(
                            text="Analyze this video forensically and return your complete assessment as JSON."
                        )
                    ]
                )
            ],
            config=types.GenerateContentConfig(
                system_instruction=SYSTEM_PROMPT,
                temperature=0.1,
                max_output_tokens=4096,
                response_mime_type="application/json"
            )
        )

        raw = response.text.strip()
        raw = re.sub(r'^```(?:json)?\s*', '', raw, flags=re.MULTILINE)
        raw = re.sub(r'\s*```$', '', raw, flags=re.MULTILINE)
        raw = raw.strip()

        try:
            return json.loads(raw)
        except json.JSONDecodeError:
            match = re.search(r'\{.*\}', raw, re.DOTALL)
            if match:
                try:
                    return json.loads(match.group())
                except json.JSONDecodeError:
                    pass
            print(f"JSON parse failed, raw: {raw[:300]}")
            return None

    except Exception as e:
        print(f"Gemini analysis error: {e}")
        return None

def cleanup_gemini_file(gemini_file):
    try:
        gemini_client.files.delete(name=gemini_file.name)
    except Exception:
        pass

def cleanup_local_file(path: Path):
    try:
        if path.exists():
            path.unlink()
    except Exception:
        pass

def build_layer(raw: dict, key: str) -> LayerResult:
    layer = raw.get(key, {})
    status = layer.get("status", "warn")
    label_raw = layer.get("label", "Unable to assess")
    detail = layer.get("detail", "Insufficient data for this layer.")
    prefix = {"pass": "✓", "fail": "✕", "warn": "⚠"}.get(status, "⚠")
    return LayerResult(status=status, label=f"{prefix} {label_raw}", detail=detail)

def build_info_layer(raw: dict) -> InfoResult:
    layer = raw.get("information_integrity", {})
    severity = layer.get("severity", "none")
    label_raw = layer.get("label", "No integrity issues found")
    detail = layer.get("detail", "No factual claims requiring verification were detected.")
    return InfoResult(severity=severity, label=label_raw, detail=detail)


@app.get("/")
def root():
    return {"status": "ok", "service": "HCA Verify API"}

@app.get("/health")
def health_check():
    return {"status": "ok"}

@app.post("/verify", response_model=VerifyResponse)
async def verify_video(req: VerifyRequest):
    if not GEMINI_API_KEY:
        raise HTTPException(500, "GEMINI_API_KEY not configured")

    url = req.url.strip()
    if not url.startswith("http"):
        raise HTTPException(400, "Invalid URL")

    scan_id = make_scan_id()
    platform = detect_platform(url)
    video_path = TEMP_DIR / f"{scan_id}.mp4"

    try:
        downloaded = await download_video(url, video_path)
        if not downloaded:
            raise HTTPException(422, "Could not download video. The link may be private, expired, or unsupported.")

        gemini_file = upload_to_gemini(video_path)
        cleanup_local_file(video_path)

        if not gemini_file:
            raise HTTPException(500, "Failed to process video for analysis.")

        result = analyze_with_gemini(gemini_file)
        cleanup_gemini_file(gemini_file)

        if not result:
            raise HTTPException(500, "Analysis failed. Please try again.")

        score = max(0, min(100, int(result.get("score", 50))))
        verdict = result.get("verdict", "human" if score >= 68 else "ai")
        if verdict not in ("human", "ai"):
            verdict = "human" if score >= 68 else "ai"

        title = "Human-Made Content" if verdict == "human" else "AI-Generated Signals Detected"

        findings = result.get("findings", [
            "Analysis complete.",
            "See layer breakdown above for details.",
            "Contact HCA if you believe this result is incorrect."
        ])
        while len(findings) < 3:
            findings.append("No additional findings.")
        findings = findings[:3]

        return VerifyResponse(
            success=True,
            score=score,
            verdict=verdict,
            title=title,
            platform=platform,
            scan_id=scan_id,
            video_frames=build_layer(result, "video_frames"),
            audio_signal=build_layer(result, "audio_signal"),
            face_analysis=build_layer(result, "face_analysis"),
            metadata=build_layer(result, "metadata"),
            script_analysis=build_layer(result, "script_analysis"),
            overall=LayerResult(
                status="pass" if verdict == "human" else "fail",
                label="HMC Eligible" if verdict == "human" else "Not HMC Eligible",
                detail=(
                    "This content qualifies for HMC certification. Apply to receive your certificate and watermark."
                    if verdict == "human" else
                    "This content does not qualify for any HMC tier based on the signals detected."
                )
            ),
            information_integrity=build_info_layer(result),
            findings=findings
        )

    except HTTPException:
        raise
    except Exception as e:
        cleanup_local_file(video_path)
        raise HTTPException(500, f"Unexpected error: {str(e)}")
